name: locator_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.2.6
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  path: any
  uuid: ^4.2.1
  logger: ^2.0.2+1
  fluster: ^1.2.0
  image: ^4.1.3
  geolocator: ^10.1.0
  intl: ^0.18.1
  geocoding: ^2.1.1
  expandable: ^5.0.1
  expansion_tile_group: ^1.2.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
  - family: WorkSans 
    fonts:
      - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
      - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
        style: italic
      - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        weight: 300
      - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
      - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
      - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
      - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
